Repository theohbrothers/ConvertOneNote2MarkDown, pull requests merged in 2022-07, with the labels that each got.

#120 Fix: Fix keepspaces option to work with nested lists
  ConvertOneNote2MarkDown-v2.Tests.ps1
  ConvertOneNote2MarkDown-v2.ps1
Labels: fix

#118 Fix: Search recursively for all attachment(s)
  ConvertOneNote2MarkDown-v2.Tests.ps1
  ConvertOneNote2MarkDown-v2.ps1
Labels: fix

#128 Docs (readme): Add 'Common Errors' section in readme
  README.md
Labels: docs

#129 Fix (logging): Fix error logging to be more readable
  ConvertOneNote2MarkDown-v2.ps1
Labels: fix

#130 Docs (readme): Add more errors under 'Common errors' section
  README.md
Labels: docs

#131 Docs (ci): Cleanup Bug Report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: docs, area/ci

#132 Enhancement (ci): Add `windows-2022` test job
  .github/workflows/ci-master-pr.yml
Labels: enhancement, area/ci

#134 Fix (regression): Fix `headerTimestampEnabled` to add a newline between header separator and page content
  ConvertOneNote2MarkDown-v2.Tests.ps1
  ConvertOneNote2MarkDown-v2.ps1
Labels: fix

#135 Docs (configuration): Add comments for `conversion` config option about pandoc extension(s) needing to be supported by user's pandoc version
  ConvertOneNote2MarkDown-v2.ps1
  config.example.ps1
Labels: docs
